### ISSUE TITLE
Visual Studio for Mac support?

### ISSUE THREAD

**Issue by victoragung** [mikeyjones/SpecFlow#9]
Hi Mikey,

Any chance the package could be updated to support the Visual Studio for Mac preview?
I assume it's similar to Xamarin Studio 6.1.

Cheers,
Victor

**Comment by jimbobbennett** [comment]
Just raised a PR for this

https://github.com/mikeyjones/SpecFlow/pull/10

**Comment by brianjmitchell** [comment]
I have imported the Xamarin Studio 6 "mpack" for VS for Mac and it seems to work.

**Comment by ademanuele** [comment]
Currently, the SpecFlow extension does not work on Visual Studio for Mac 2017, released not long ago.

Attempting to install complains that:
Required: MonoDevelop.Core v6.0, found v7.0
Required: MonoDevelop.Ide v6.0, found v7.0

**Comment by jimbobbennett** [comment]
@ademanuele - We have a working mpack for it - https://github.com/straighteight/SpecFlow-VS-Mac-Integration/releases

I'm also working on a big refactoring to use the SpecFlow nuget packages instead of having the code bought in. It's working, but just like my first attempt at the VS for Mac port it's missing syntax highlighting. I'm trying to get that done then will raise a big PR with it all in.

**Comment by mikeyjones** [comment]
Thanks @jimbobbennett this is brilliant.

Jim and I will try and get the Jim's pull request in ASAP, then we can get them pack in to realeases and VS for mac's add in area

**Comment by jimbobbennett** [comment]
Support for Vs for Mac has moved to https://github.com/straighteight/SpecFlow-VS-Mac-Integration
